### ISSUE TITLE
Let's find a new name for gpass

### ISSUE THREAD

**Issue by yakuter** [pass-wall/passwall-api#10]
When I starting this project, this was just a weekend project. However, now I think it should have a future.

Today, I searched internet and found gpass.io, which is also a password manager. I think we should better find a new name.

Any suggestions?

**Comment by ionutale** [comment]
I like small names

How about “vault”

**Comment by yakuter** [comment]
> vault

Unfortunately Hashicorp has a project with vault.

https://www.vaultproject.io/

**Comment by yakuter** [comment]
PassWall is the name I’ve chosen.
