### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by yakuter** [pass-wall/passwall-api#32]
Users should be able to pull from docker easily

**Comment by mehmetka** [comment]
Hi, 
I created an organization called passwall and pushed image to docker hub.

You can pull:
$ docker pull passwall/passwall-api

**Comment by yakuter** [comment]
Great news. I will try it. Do you mind making me member at that organization. I would like to update image time to time.

**Comment by mehmetka** [comment]
Done, I added.

**Comment by yakuter** [comment]
I just tested it. It is works great! Thank you so much.
