### ISSUE TITLE
Url parse

### ISSUE THREAD

**Issue by aeosmanoglu** [pass-wall/passwall-api#36]
if put/post body like that when we create/update a login

```json
{
	"URL":"notwebsite.com",
	"Username": "not@not.com",
	"Password": "notpassword"
}
```

it response like that

```json
{
  "ID": 2,
  "URL": "",
  "Username": "not@not.com",
  "Password": "notpassword"
}
```

Can you fix it?

**Comment by yakuter** [comment]
Hello, I fixed this. You can pull updated repo or do your tests on Heroku demo site:
 
https://passwall-api-demo.herokuapp.com/
<img width="641" alt="Screen Shot 2020-04-17 at 20 25 55" src="https://user-images.githubusercontent.com/3696314/79596737-c6d7fb00-80e9-11ea-9fb1-54a73490772d.png">
